#' Generate Samples from a Gaussian Mixture Model
#'
#' Generates random samples from a multivariate mixture of Gaussians (MMN) distribution
#' with specified mixture proportions, means, and covariance matrices.
#'
#' @param N Integer. Number of observations to generate.
#' @param D Integer. Dimension of the distribution (number of features per observation).
#' @param Tau A numeric vector of length \eqn{k} specifying mixture proportions.
#'   Must be non-negative and sum to 1. Will be normalized if not.
#' @param Mu A list of length \eqn{k}, each element a numeric vector of length \eqn{D}
#'   specifying the mean of one mixture component.
#' @param Sigma A list of length \eqn{k}, each element a \eqn{D \times D}{D x D} covariance matrix
#'   specifying the covariance of one mixture component.
#'
#' @return An \eqn{n \times D}{n x D} matrix of samples from the mixture model, where
#'   \eqn{n \approx N} (exact value depends on rounding in allocation to components).
#'
#' @details
#' Samples are generated by:
#' 1. Draw component allocations from a multinomial distribution with probabilities \eqn{\tau_j}{tau_j}.
#' 2. Generate samples from each component using multivariate normal distribution.
#' 3. Combine samples into a single matrix.
#'
#' @examples
#' \dontrun{
#' # Generate data from a mixture of 2 bivariate Gaussians
#' Tau <- c(0.3, 0.7)
#' Mu <- list(c(0, 0), c(5, 5))
#' Sigma <- list(diag(2), diag(2))
#' X <- rmmnorm(N = 100, D = 2, Tau = Tau, Mu = Mu, Sigma = Sigma)
#' }
#'
#' @importFrom MASS mvrnorm
#' @importFrom stats rmultinom
#' @export

rmmnorm <- function(N, D, Tau, Mu, Sigma) {
  if (!is.numeric(N) || length(N) != 1 || !is.finite(N) || N < 1) {
    stop("N must be a positive scalar.")
  }
  if (!is.numeric(D) || length(D) != 1 || !is.finite(D) || D < 1) {
    stop("D must be a positive scalar.")
  }
  N <- as.integer(N)
  D <- as.integer(D)
  if (!is.numeric(Tau) || length(Tau) < 1 || any(!is.finite(Tau)) || any(Tau < 0)) {
    stop("Tau must be a non-negative numeric vector with finite values.")
  }
  if (sum(Tau) <= 0) {
    stop("Tau must have positive sum.")
  }

  K <- length(Tau)
  if (!is.list(Mu) || !is.list(Sigma) || length(Mu) != K || length(Sigma) != K) {
    stop("Mu and Sigma must be lists of length length(Tau).")
  }
  if (!all(vapply(Mu, function(m) is.numeric(m) && length(m) == D, logical(1)))) {
    stop("Each Mu[[k]] must be a numeric vector of length D.")
  }
  if (!all(vapply(Sigma, function(s) is.matrix(s) && all(dim(s) == c(D, D)), logical(1)))) {
    stop("Each Sigma[[k]] must be a D x D matrix.")
  }

  Tau <- Tau / sum(Tau)
  counts <- as.vector(stats::rmultinom(1, size = N, prob = Tau))
  Normal <- vector("list", K)

  for (ii in seq_len(K)) {
    if (counts[ii] > 0) {
      Normal[[ii]] <- MASS::mvrnorm(n = counts[ii], Mu[[ii]], Sigma[[ii]])
    } else {
      Normal[[ii]] <- matrix(numeric(0), ncol = D)
    }
  }

  X <- do.call("rbind", lapply(Normal, function(z) matrix(z, ncol = D)))
  return(X)
}
